version: 2.1

parameters:
  trigger:
    type: boolean
    default: true

  api:
    type: boolean
    default: false
  app:
    type: boolean
    default: false

  init:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: circleci/node:12.4.0-stretch

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      - run:
          name: Content
          command: |
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

  initialize:
    executor: node
    steps:
      - run:
          name: Initalize Pipeline
          command: echo "Let's build!"

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_name: api
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app:
    when: << pipeline.parameters.app >>
    jobs:
      - build:
          name: app-build
          package_name: app
  initialize:
    when: << pipeline.parameters.init >>
    jobs:
      - initialize
